#!/bin/bash

#export ANDROID_BUILD_TOP=/brillo/
#export ANDROID_TOOLCHAIN=/brillo/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin
#export ANDROID_PRODUCT_OUT=/brillo/out/target/product/gert/

# Cross compile
mkdir -p build/brillo/out
pushd build/brillo/out
cmake -DCMAKE_TOOLCHAIN_FILE=../../../makefiles/cmake/toolchains/arm-linux-androideabi.cmake -DCMAKE_BUILD_TYPE=Release ../../../
make
make install ${ANDROID_PRODUCT_OUT}/system
popd

