#!/bin/bash

#export ANDROID_BUILD_TOP=/brillo/
#export ANDROID_TOOLCHAIN=/brillo/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin
#export ANDROID_PRODUCT_OUT=/brillo/out/target/product/pete/
export TOOLCHAIN=makefiles/cmake/toolchains/aarch64-linux-android.cmake

# Cross compile
mkdir -p build/brillo64/out
pushd build/brillo64/out
cmake -DLOCAL_TOOLCHAIN=$TOOLCHAIN -DCMAKE_TOOLCHAIN_FILE=../../../$TOOLCHAIN -DCMAKE_BUILD_TYPE=Release ../../../
make
#make install DESTDIR=${ANDROID_PRODUCT_OUT}/obj/gentoo/root
popd

